services:
  guacamole-guacd:
    image: guacamole/guacd
    networks:
      - proxy
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  guacamole-postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_database
      POSTGRES_PASSWORD: 'Passw0rd!'
      POSTGRES_USER: db_user
    image: postgres:15.2-alpine
    networks:
      - proxy
    restart: always
    volumes:
    - ./db_init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  guacamole:
    image: guacamole/guacamole
    group_add:
      - "1000"
    restart: always
    environment:
      GUACD_HOSTNAME: guacamole-guacd
      POSTGRESQL_HOSTNAME: guacamole-postgres
      POSTGRESQL_DATABASE: guacamole_database
      POSTGRESQL_USER: db_user
      POSTGRESQL_PASSWORD: 'Passw0rd!'
      RECORDING_SEARCH_PATH: /record
    networks:
      - proxy
    volumes:
      - ./record:/record:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.rule=Host(`server-console.duckdns.org`)"
      - "traefik.http.routers.guacamole.entrypoints=websecure"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.tls.certresolver=le"
      - "traefik.http.middlewares.guac-add-prefix.addprefix.prefix=/guacamole"
      - "traefik.http.routers.guacamole.middlewares=guac-add-prefix@docker"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
#    ports:
#      - 8080:8080/tcp 

networks:
  proxy:
    name: traefik-proxy
