
[Dialer orange]
Init1 = ATZ
Modem = /dev/ttyUSB_huawei
Init3 = AT+CGDCONT=1,"IP","internet"
Username = "internet"
Password = "internet"
Phone = "*99#"
Dial Command = ATDTW
Stupid Mode = yes
Dial Attempts = 0
Auto Reconnect = on
Check Def Route = on

[Dialer aero]
Init1 = ATZ
Modem = /dev/ttyUSB_huawei
Init3 = AT+CGDCONT=1,"IP","darmowy"
Phone = "*99#"
Dial Command = ATDTW
Stupid Mode = yes
Dial Attempts = 0
Auto Reconnect = on
Check Def Route = on
Username = " "
Password = " "
